### ISSUE TITLE
Write externs for p5.js to allow using advanced compilation mode

### ISSUE THREAD

**Issue by oakes** [oakes/play-cljs#1]
I currently have to compile with `:optimizations :simple` because there are no externs written for p5.js and p5.tiledmap.js.

**Comment by sir-pinecone** [comment]
Hey Zack, I just came across this moments ago while looking at the [Pixi cljsjs](https://github.com/cljsjs/packages/tree/master/pixi) readme. Maybe this can help you out? https://github.com/jmmk/javascript-externs-generator

**Comment by oakes** [comment]
Hey @sir-pinecone sorry for not responding earlier. I am going to use the upcoming inferred externs feature in ClojureScript to generate the externs for me.

**Comment by sir-pinecone** [comment]
No problem Zack. I just saw a post on that new feature. Good stuff 👍

Michael

**Comment by oakes** [comment]
This can now be closed, because 0.10.0 comes with support for the inferred externs feature, thus allowing advanced compilation.
