### ISSUE TITLE
p5 interop and raw canvas question

### ISSUE THREAD

**Issue by BorisKourt** [oakes/play-cljs#10]
1: What is a good way to setup p5 functionality like: https://p5js.org/reference/#/p5/touchEnded 

2: I was trying to also setup [Touch Events](https://developer.mozilla.org/en/docs/Web/API/Touch_events) for the canvas element, but trying to use `get-canvas` like this:

```clojure
(let [^js/Element el (p/get-canvas game)] 
        (. el addEventListner "touchend" handler-fn false))
```

give me `TypeError: el.addEventListner is not a function`

Did I forget something basic there?

Thanks,
Boris

**Comment by oakes** [comment]
You have a typo :) You wrote addEventListner instead of addEventListener.

**Comment by BorisKourt** [comment]
Ooof that is embarrassing :) Re-typed it so much that I couldn't imagine it would be a typo after a while. 

What about the earlier question, can I reference all of p5 functionality or is only a subset supported?

Thanks for catching the typo!

**Comment by oakes** [comment]
No worries!
