### ISSUE TITLE
Should there be a push/pop surrounding the p5.scale call in draw-sketch! :image?

### ISSUE THREAD

**Issue by rsnara** [oakes/play-cljs#4]
[Relevant Code](https://github.com/oakes/play-cljs/blob/master/src/play_cljs/core.cljs#L195)

As far as I know, p5.scale affects all subsequently drawn shapes: [P5 Docs](https://p5js.org/reference/#/p5/scale). 

If I try to draw two images, the scale from the first will bleed into the second, which is unexpected.

```Clojure
(p/render game [[:image {:name "durr.png" :scale-x 2 :x 0 :y 0}]
                [:image {:name "hurr.png" :scale-x 2 :x 10 :y 10}]])
```

**Comment by oakes** [comment]
Fixed by your PR, thanks!
